---

- hosts: localhost
  become: true


  tasks:

  - name: Remove the ingest-geoip plugin if existing
    command: /usr/share/elasticsearch/bin/elasticsearch-plugin remove ingest-geoip --purge
    ignore_errors: yes

  - name: Add the ingest-geoip plugin to Elasticsearch
    command: /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///opt/ingest-geoip.zip --batch

  - name: Remove the ingest-user-agent plugin if existing
    command: /usr/share/elasticsearch/bin/elasticsearch-plugin remove ingest-user-agent --purge
    ignore_errors: yes

  - name: Add the ingest-user-agent plugin to Elasticsearch
    command: /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///opt/ingest-user-agent.zip --batch

  - name: Change Elasticsearch's minimum memory usage to 512MB
    lineinfile:
      path: /etc/elasticsearch/jvm.options
      regexp: "^-Xms"
      line: "-Xms512m"
      state: present

  - name: Change Elasticsearch's maximum memory usage to 512MB
    lineinfile:
      path: /etc/elasticsearch/jvm.options
      regexp: "^-Xmx"
      line: "-Xmx512m"
      state: present

  - name: Do not swap
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: "bootstrap.memory_lock"
      line: "bootstrap.memory_lock: true"
      state: present

  - name: We only have a single node, set minimum master nodes accordingly
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: "discovery.zen.minimum_master_nodes"
      line: "discovery.zen.minimum_master_nodes: 1"
      state: present

  - name: Require explicit names when deleting indices
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: "action.destructive_requires_name"
      line: "action.destructive_requires_name: true"
      state: present

  - name: Disable watermarks, since disk space might be tight on the 10GB base box
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: "cluster.routing.allocation.disk.threshold_enabled"
      line:  "cluster.routing.allocation.disk.threshold_enabled: false"
      state: present

  - name: Enable monitoring of the Elastic Stack
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: "xpack.monitoring.collection.enabled"
      line:  "xpack.monitoring.collection.enabled: true"
      state: present

  - name: Set the right ulimits
    shell: ulimit -n 65536
  - shell: ulimit -l unlimited

  - name: Start Elasticsearch
    service: name=elasticsearch state=restarted

  - name: Wait for Elasticsearch to become available
    wait_for:
      port: 9200
      delay: 5

  - name: Set the number of shards to one and the number of replicas to 0
    uri:
      url: http://localhost:9200/_template/template_global
      body_format: json
      method: PUT
      body:
        template: "*"
        order: 0
        settings:
          number_of_shards: 1
          number_of_replicas: 0
      status_code:
        - 200
        - 201
