---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Heartbeat configuration
    template: src=templates/heartbeat.yml dest=/etc/heartbeat/heartbeat.yml

  - name: Restart Heartbeat
    service: name=heartbeat-elastic state=restarted
